### DISCUSSION TITLE
date in CSV - includes timestamp, won't import

### DISCUSSION THREAD

**Discussion by sprucas** [nielsmaerten/ynab-buddy#245] [General]
Hi Niels,
I got ynab-buddy up and running on my Debian shell
Setup the config.yaml - but when running the tool, it seems to insert a datetime into date field - YNAB throws an error that it can't recognize the date field
Here is an example
Amount,Date,Memo
78.67,2024-04-28T00:00:00.000Z,COLES
If I manually trim the timestamp - T00:00:00.000Z - I can import no problems
Is it something I need to configure on my end
Thanks
sprucas

**Comment by nielsmaerten** [comment]
_Huh... that's weird. 🤔_
 Which is just programmer-speak for: "It shouldn't be doing that, I'll look into it" ;)

To help me reproduce the issue, could you also share one of your CSV's lines and the "parsers" section of your config file?

**Comment by sprucas** [comment]
Here is the parser for my AMEX CSVs
```yaml
  - name: amex-parser
    # Number of header and footer rows to skip when parsing the file.
    header_rows: 1
    footer_rows: 0
    # Delimiter used to separate columns in the CSV file (e.g., ";", ",", "\t").
    delimiter: ","
    # Define the columns in the CSV file.
    # Use 'skip' to ignore a column.
    # Use 'amount' if both inflow and outflow are in the same column. Negative amounts will be treated as outflows.
    columns: [date, skip, memo, skip, skip, amount, in_out_flag]
    outflow_indicator: "OUT"
    # Date format used in the CSV file (e.g., M/d/yyyy, d-M-yyyy).
    # See https://moment.github.io/luxon/#/parsing?id=table-of-tokens for a list of supported formats.
    date_format: dd/MM/yyyy
    # Decimal and thousand separators used in the CSV file (e.g., ".", ",").
    decimal_separator: "."
    thousand_separator: "" # Leave empty if not used
```
Here is the original file, anonymized
[activity.csv](https://github.com/nielsmaerten/ynab-buddy/files/15160596/activity.csv)

Here is a ynab-buddy file, nothing too secret in here
[amex-.YNAB.csv](https://github.com/nielsmaerten/ynab-buddy/files/15160508/amex-.YNAB.csv)

**Reply by nielsmaerten** [reply]
Ok, this took me longer than it should have, but I think I figured it out 😅

Correct me if I'm wrong: You're not letting ynab-buddy upload your transactions, right?  
Instead you use it to create a ynab-compatible CSV file, which you then drop into YNAB yourself?

It looks like there's a bug in the way these CSV files are generated.  
They indeed get a full timestamp, where it should only be the date.  
Bug will be fixed ASAP: https://github.com/nielsmaerten/ynab-buddy/issues/246
If you're using npm, you can get the early release of this fix by running `npm i -g ynab-buddy@next`

**Comment by sprucas** [comment]
okay, pulled your next build with `npm i -g ynab-buddy@next`

re-enabled ynab-buddy to upload, set config.yaml to keep parsed_file and keep original_file

```yaml
  - account_name: Amex
    # File name pattern to match for this account's transactions (e.g., BNP-export-IBAN01233456789-*.csv).
    pattern: amex-*.csv
    # Parser to use for processing this account's transactions.
    parser: amex-parser
    # YNAB account and budget IDs for uploading transactions.
    ynab_account_id: xxxx-yyyy-zzzz
    ynab_budget_id: aaaa-bbbb-cccc
    # Optional flag color for uploaded transactions in YNAB (e.g., purple, blue, green, yellow, red, orange).
    # Place a # in front of the line to use the default (no flag).
    ynab_flag_color: purple
    # Set to true to upload transactions to YNAB; false to skip uploading.
    # Place a # in front of the line to use the default (see 'upload_transactions' below).
    upload: true
    # Set to true to save a parsed file (in YNAB CSV format) after processing; false to skip saving.
    save_parsed_file: true
    # Set to true to delete the original bank transaction file after processing; false to keep the file.
    delete_original_file: false
```

run ynab-buddy, and get this result
```
anon@OFFICE-PC:/$ ynab-buddy

*********************
YNAB Buddy (v2.0.2-0)
*********************
Using configuration file:
/home/anon/ynab-buddy/config.yaml

Found 1 file(s) eligible for parsing.

Parsing: /home/anon/bank/amex/amex-.csv
Success: 6 transactions parsed.

Error while uploading transactions to YNAB.
Ensure your config file has a valid token, budgetID and accountID
Error detail: {"error":{"id":"404.2","name":"resource_not_found","detail":"Resource not found"}}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "UPLOAD ERROR".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.13.0
```

since ynab-buddy configured to keep the parsed file - i checked it out and found timestamp still exists

output of amex-.YNAB file
```
Amount,Date,Memo
125,2024-05-01T00:00:00.000Z,MEMBERSHIP FEE
15.66,2024-04-30T00:00:00.000Z,AMAZON AU               SYDNEY SOUTH
49.95,2024-04-29T00:00:00.000Z,APPLE.COM/BILL          SYDNEY
53,2024-04-29T00:00:00.000Z,COLES ASQUITH 760       ASQUITH
5.6,2024-04-29T00:00:00.000Z,TALYLORS PATISSERIE PTY CASTLE HILL
24.8,2024-04-29T00:00:00.000Z,WITHAMS COFFEE SPECIALT HORNSBY
```

I have triple-checked the valid token, budgetID and accountID - they are correct.
I assume the UPLOAD_ERROR returned by YNAB is due to date/time - since with the timestamp YNAB can't seem to identify the date field correctly, that is because if I try to drag/drop the parsed file into YNAB directly - it complains about the date.

Thanks for your help
sprucas
