### DISCUSSION TITLE
ING Columns

### DISCUSSION THREAD

**Discussion by DavidJinho** [nielsmaerten/ynab-buddy#28] [Q&A] [answered]
Hi Niels,

Thanks for creating this tool! I'm trying to set it up for my ING account however not sure how I should set up the columns.

ING provides me with:
Date, Payee, Account, Counterparty, Code, Debit/Credit, Amount, Transaction Type, Notifications, Resulting Balance, Tag

Could you tell me how to do this correctly? Also, there is no column for inflow and outflow, all amounts are in one column and the previous debit/credit column indicates if its an outflow or inflow.

Thanks,
David

**Comment by nielsmaerten** [comment, marked as answer]
Hi David,
You're going to want to try the [v1.1.0 preview](https://github.com/nielsmaerten/ynab-buddy/releases/tag/v1.1.0-preview.1). This new version supports the column layout you're describing.

Here's an example of what your parser configuration could look like: 
```yaml
- name: ing-checking
  header_rows: 1
  footer_rows: 0
  delimiter: ";"
# Date, Payee, Account, Counterparty, Code, Debit/Credit, Amount, Transaction Type, Notifications, Resulting Balance, Tag
  columns: [date,payee,skip,skip,skip,in_out_flag,amount,skip,memo,skip,skip]
  outflow_indicator: "Af"
  date_format: yyyy/MM/dd
```

Note the new *"in_out_flag"* column and the *"outflow_indicator"*:  
If the value in the column *"in_out_flag"* is 'Af', the number in _"amount"_ will be treated as outflow. Otherwise, ynab-buddy will assume it's inflow.

Hope this works for you!
I'm still testing out v1.1.0, so let me know if you run into any bugs ;)
